# Generated by Django 4.2.1 on 2023-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLBase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('short_url', models.URLField(max_length=30)),
            ],
        ),
    ]
