# Generated by Django 4.2.1 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='urlbase',
            table='url_base',
        ),
    ]
