# Generated by Django 4.2.1 on 2023-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_alter_urlbase_id_alter_urlbase_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlbase',
            name='short_url',
            field=models.URLField(max_length=30, unique=True),
        ),
    ]
